### ISSUE TITLE
Recent releases seemingly missing from github releases list

### ISSUE THREAD

**Issue by claremacrae** [SimonCropp/MarkdownSnippets#100]
#### Describe the bug

The github releases page only goes up to 16.1.1 on 3 August.
https://github.com/SimonCropp/MarkdownSnippets/releases

The milestone of this issue suggests there was at least a 16.4.2 release:
https://github.com/SimonCropp/MarkdownSnippets/issues/89

And this output suggests that the current version is 16.5.0

```
$ dotnet tool update  -g MarkdownSnippets.Tool
error NU1202: Package MarkdownSnippets.Tool 16.5.0 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2) / any. Package MarkdownSnippets.Tool 16.5.0 supports: netcoreapp3.0 (.NETCoreApp,Version=v3.0) / any
Tool 'markdownsnippets.tool' failed to update due to the following:
The tool package could not be restored.
Tool 'markdownsnippets.tool' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.
```

#### Minimal Repro

Open https://github.com/SimonCropp/MarkdownSnippets/releases

**Comment by claremacrae** [comment]
I was doing this because I wanted to look at the recent changes - and in particular to see if any release notes showed how to update .Net Core, and what the last pre-.Net Core version 3 version was.

(I was also curious as to whether the move to .Net Core constituted a breaking change which warranted bumping the major version nu,ber...)

**Comment by SimonCropp** [comment]
as per "where are the release notes". i use [closed milestones](https://github.com/SimonCropp/MarkdownSnippets/milestones?state=closed) for that. It is linked from [the main readme](https://github.com/SimonCropp/MarkdownSnippets#release-notes) and from [the nuget](https://www.nuget.org/packages/MarkdownSnippets.Tool/)

netcore is stable and can be downloaded from https://dotnet.microsoft.com/download

> whether the move to .Net Core constituted a breaking change which warranted bumping the major version number

yep since it requires people to install a new runtime

> github releases page only goes ...

for some strange reason github autocreates a release every time you create a tag. i was a bit behind on my tagging. i have fixed that.
