### ISSUE TITLE
allow /source/ directories

### ISSUE THREAD

**Issue by isidore** [SimonCropp/MarkdownSnippets#24]
#### Too many files
I am loving MarkdownSnippets and it is helping to have me create more documentation than ever before. The issue is it creates a lot of files in the directories.

For example: https://github.com/approvals/ApprovalTests.cpp/tree/master/doc

This creates a sort of decision paralysis when reading docs.

#### seperate /source/ subdirectory 

It would be nice to have
/docs/source/Contributing.source.md
compile to
/docs/Contributing.md

The idea would be if the directory right in front of a .source.md file is source, it is also removed.

#### Describe alternatives considered

don't really have an alternative at the moment.

#### Additional context

To be clear, I still want the existing behavior as well. just the option of putting the docs in a source subdirectory when they get to numerous.

Thanks!

**Comment by SimonCropp** [comment]
Essentially what i have done here https://github.com/Fody/Home/tree/master/pages 

I will look into it

**Comment by isidore** [comment]
yeah, is that an existing feature I missed?
btw: i still think the source files should have the source prefix.

**Comment by SimonCropp** [comment]
> is that an existing feature I missed?

nah i build that one using the .net  API, so it wont work for the console app

**Comment by SimonCropp** [comment]
i would prefer 

/docs.source/Contributing.md
compile to
/docs/Contributing.md

thoughts?

**Comment by claremacrae** [comment]
Hello Simon,

How would that work for source files in the root of a project, e.g. 

https://github.com/approvals/ApprovalTests.cpp/README.source.md

https://github.com/approvals/ApprovalTests.cpp.source/README.source.md would be a whole separate project.

**Comment by claremacrae** [comment]
It has been useful to search for all *.source.md to avoid picking up loads 3rd-party files in sub-directories.

**Comment by SimonCropp** [comment]
@claremacrae but doesnt the same problem exist with @isidore proposal of 

/docs/source/Contributing.source.md
compile to
/docs/Contributing.md

**Comment by claremacrae** [comment]
I don't think so...

I read @isidore proposal as any /source/ would get replaced by / 

/source/README.source.md
compiles to
/README.md

Looking at this now, it might be odd for projects that /include and /source - which would not be unusual for a C++ project - to have both program source code and markdown source code in the source directory.

**Comment by claremacrae** [comment]
Or we could leave root-level .source.md at the root, and have them converted to .md as currently...

**Comment by SimonCropp** [comment]
ok happy to consider a PR for this

**Comment by SimonCropp** [comment]
one thing i dont understand is why if we have `source` in the dir, why we would need the `.source.md` suffix as well?

**Comment by isidore** [comment]
consistency

**Comment by SimonCropp** [comment]
i went with `/mdsource/` instead of  `/source/`

can u try 10.0.0-beta.3

**Comment by claremacrae** [comment]
Thanks Simon. I've tried it out on a branch [`mdsnippets_source_dir`](https://github.com/approvals/ApprovalTests.cpp/tree/mdsnippets_source_dir) and it's working really well... I like the name `/mdsource/` - it's clear, and less likely to be already used than source.

Some comments that I only realised after using it (@isidore, please note...)

* Not having pairs of .md files makes it much easier to browse markdown files: https://github.com/approvals/ApprovalTests.cpp/tree/mdsnippets_source_dir/doc
* However, in .source.md files, it does risk breaking references to relative paths - examples:
  * in [root/README.source.md](https://github.com/approvals/ApprovalTests.cpp/blob/mdsnippets_source_dir/mdsource/README.source.md), the "Intro Graphic" is a broken link, instead of embedding the image
  * in all our docs/mdsource/*.source.md e.g. [Troubleshooting.source.md](https://github.com/approvals/ApprovalTests.cpp/blob/mdsnippets_source_dir/doc/mdsource/Troubleshooting.source.md), the "Back to User Guide" links at the bottom all give 404s now.

With use, I think we'll learn how to work around these, e.g. we can get in the habit of giving full paths (well, from root) in these links/references, so that they work (and can be tested) whilst editing .source.md files. And we can update our [Contributing](https://github.com/approvals/ApprovalTests.cpp/blob/master/doc/Contributing.md#documentation) notes to record tips.

Overall, I think this is a huge usability improvement, both for those reading the docs and for those editing

**Comment by claremacrae** [comment]
Hi @SimonCropp 

In case it helps with documenting this feature, I've done some experimenting with relative links. The two files are:

* https://github.com/approvals/ApprovalTests.cpp/blob/mdsnippets_source_dir/doc/TestRelativeLinks.md
* https://github.com/approvals/ApprovalTests.cpp/blob/mdsnippets_source_dir/doc/mdsource/TestRelativeLinks.source.md

In case it helps for documenting this feature, the conclusion is - for github at least:

"If putting your `.source.md` files in a `mdsource` sub-directory, all references to other files, such as hyperlinks and images, should specify the full path from the root of your repository, so that they work correctly in both the source and generated markdown files. Use of relative paths won't work in both copies of your file."

The wording could probably be improved, but I hope it's helpful...

**Comment by SimonCropp** [comment]
v 10 stable has been released.

**Comment by SimonCropp** [comment]
@claremacrae thanks for the doco content. i used some of it here https://github.com/SimonCropp/MarkdownSnippets#mdsource-directory-convention

**Comment by claremacrae** [comment]
@SimonCropp  Fabulous - thanks - nice wording.

Trivaa: Is there a typo in the docs? In one place it refers to `mssnippets`?

> There is a secondary convention that leverages the use of a directory named mssnippets.

**Comment by SimonCropp** [comment]
@claremacrae yes u r correct. fixed, thanks

**Comment by claremacrae** [comment]
@SimonCropp Erm - sorry if I'm missing something obvious.

Now it says `mdsnippets` - I thought it should say `mdsource`?

**Comment by SimonCropp** [comment]
fixed
