### ISSUE TITLE
Change convention for defining snippets

### ISSUE THREAD

**Issue by SimonCropp** [SimonCropp/MarkdownSnippets#46]
change convention to 
```
// begin-snippet: MySnippetName
My Snippet Code
// end-snippet
```

old convention is considered obsolete but still supported

**Comment by SimonCropp** [comment]
paging @claremacrae  @isidore

**Comment by claremacrae** [comment]
Funnily enough, here is something I sent to @isidore recently;

I realised why I’m struggling to remember the syntax for snippets:

We have:

// begincode: blah
// endcode
snippet: blah

If it was snippet instead of code, I would remember all 3 lines without looking it up:

// beginsnippet: blah
// endsnippet
snippet: blah

I know it’s too late to change it...

**Comment by claremacrae** [comment]
Simon, In your example I think you use snippet: for two different things, and that could be confusing.

**Comment by SimonCropp** [comment]
@claremacrae 

its not to late to change it. the code for parsing snippets is setup as key-value pair functions.
https://github.com/SimonCropp/MarkdownSnippets/blob/master/src/MarkdownSnippets/Reading/StartEndTester.cs

And we already have two implementations when u include c# regions

so it is trivial to add an extra syntax, i am just trying to work out what that extra syntax should be

i am happy with 

```
// beginsnippet: blah
// endsnippet
```

**Comment by claremacrae** [comment]
I like that you use begin and end as a pair. 

It seems natural to me that both “begin and end”, and “start and finish”, go together- but begin the other ways round eg not “start and end”.

**Comment by SimonCropp** [comment]
> It seems natural to me that both “begin and end”, and “start and finish”, go together- but begin the other ways round eg not “start and end”.

agreed, i dont know what i was thinking

**Comment by claremacrae** [comment]
@SimonCropp just seen your reply. For me, this would really help with writing docs!

**Comment by SimonCropp** [comment]
should it be cased?
```
// beginSnippet: blah
// endSnippet
``

**Comment by atifaziz** [comment]
> should it be cased?

If you're worried about case then I would go with hyphenation instead and all lower: 

```
// begin-snippet: blah
// end-snippet
```

It's as simple, reads clearer and avoids distaste with the camels and the Pascals of the world.

**Comment by isidore** [comment]
So my preference is still:
 
In markdown:
```
snippet:  name
```
In code:
```
 // snippet: name
 // snippet: end
```

Here's my Logic:
I need to remember less and the things I need to remember are simpler.  

Things I need to remember

1) everything starts with snippet:
2) use a snippet_name
3) end your snippet

compared to (current) 

1) snippets start with snippet:
2) snippet definitions start with 'startcode (no colon)'
3) use a snippet_name 
4) end your snippet with 'endcode'

or proposed

1) snippets start with snippet:
2) snippet definitions start with 'begin-snippet:'
3) use a snippet_name 
4) end your snippet with 'end-snippet' (no colon)

**Comment by isidore** [comment]
oh, and @atifaziz has a point. 
```
 snippet: name
 // snippet: name
 // snippet: end

```
Also avoid all snake_case / CamelCase / kebab-case issues

**Comment by atifaziz** [comment]
> Things I need to remember
> 
> 1. everything starts with snippet:
> 2. use a snippet_name
> 3. end your snippet

I really like the thinking here. What if we also give more control and take inspiration from [here-docs in shell scripting](http://tldp.org/LDP/abs/html/here-docs.html)?

```
snippet: name
 // snippet: name <<END
 // END
```

Benefits I see:

- There's only `snippet:` to commit to memory.
- If you can't care to remember `snippet: end` (which can still be supported) then fallback is to go with whatever works for you!
- You can reuse the syntax you've committed to memory for shell scripting.
- It's (human) language-agnostic so while a French person may take the trouble to remember “snippet”, they can just work with `<<FIN…FIN` for the end marker.

**Comment by atifaziz** [comment]
While we are reviewing this, we should bear in mind how many of such different conventions people have to keep in mind. For example, [dotnet-try](https://github.com/dotnet/try) that just recently exploded on the scene (and I realise this is specific to .NET) is using the following convention:

    ``` cs --region collections --source-file .\myapp\Program.cs --project .\myapp\myapp.csproj 
    ⋮
    ```

It's rather long and complex and I prefer the simplicity of MarkdownSnippets and the proposals here any day. However, the appeal of giving runnable code in documentation that you can still tinker with at time of viewing is just too much and has me currently torn between the two projects. I'm not suggesting that dotnet-try should drive the decisions & conventions but that perhaps there's too much coupling going on here? I feel we should be taking the Unix philosophy to separate the parser and the merger where each does one job and does it well. There should be a default parser but it should also be possible to shell out to another as long as it provides the snippets over standard output. Then, in an ideal world, a project can settle on its own convention and doesn't have to change the docs just because of a change of tooling.

**Comment by SimonCropp** [comment]
for me `snippet: end` is no easier to remember than `end-snippet`

Also `begin` `end` being paired make more sense to me than 

```
 // snippet: name
 // snippet: end
```

I also do not like the that `snippet: end` looks like you are starting a snippet named `end`

**Comment by isidore** [comment]
it's still 4 things. It opens the pascal/snake/kebab case issue. 
and even if it's no easier for you, is it any harder?
I'll agree that  ```end-snippet``` does have the issue of a snippet named end, but I think that's a pretty small issue of confusion, especially when you have more than 1 snippet and it being paired relatively closely to the ```snippet: name``` 
Also, ```snippet:value``` pulls to the json syntax basically everyone is used to. 
If felt this become clearer to see in the [graphic](https://github.com/isidore/MdSnippet_Samples/blob/master/MarkdownSnippets.png) 
because this format required no explanation and there was a lot of information in the image already that needed to be clearer.

**Comment by SeanFeldman** [comment]
Good ideas. From what I've seen and felt:
```
snippet: name
snippet: end
```

I'd confusing. Whenever I see `snippet:` immediately expect to see it follows by the Short snippet name. After all, this is the same syntax used to achieve the opening registration of a snippet. Therefore, when I read `snippet: end`, it reads as "a snippet called end" 🙂

I do like consistently named things

```
snippet-start: name
snippet-end
```

works great for me.
1. I know I want a snippet in both cases, starting and finishing
1. When a snippet starts, all I care is a name, knowing that everything following is a part of that snippet
1. A snippet ends with `snippet-end` and that's it. Simple.

regarding hyphen in the identifier, I love it as it eases the reading. Underscore requires a shift to be pressed when typing, hyphen doesn't. Readability us as important to me as ease to remember. Since neither do I have good memory or vision anymore.

**Comment by SeanFeldman** [comment]
Aaaannd typing on phone sucks. 😂
Editted my comment.

**Comment by atifaziz** [comment]
> Underscore requires a shift to be pressed when typing, hyphen doesn't.

<kbd>Shift</kbd> is needed for both on the [French keyboard](https://en.wikipedia.org/wiki/AZERTY). Very annoying for coding. 🙄

**Comment by SeanFeldman** [comment]
It's be ok with

```
snippet start: name
snippet end
```

Having no delimiter causes the closing command to look rather weird. Alternative could be


```
snippet name
snippet
```

1. snippet is a single command to remember. And it's aligned with the intent.
1. `snippet` with `name` is a new snippet name.
1. Empty  `snippet` is an end of whatever the snippet is currently in.

Also, would make @isidore happy with or w/o French keyboard 🙂

**Comment by atifaziz** [comment]
> 3\. Empty  `snippet` is an end of whatever the snippet is currently in.

Feels too much like an error floating on its own. If we want to get rid of the “end word” then here are some ideas:

```
// snippet: name
// :snippet
```

So the terminator is the opposite of `snippet:` where its colon (`:`) followed by `snippet`. If we want to get rid of the ':' then I'd suggest:

```
// snippet name
// /snippet
```

Although in C#, this one could get confusing with triple-slash (`///`) used for code documentation.

**Comment by SeanFeldman** [comment]
Will be honest - not fond of leading colon or slash in front of `snippet`. It adds to the confusing syntax more than simplifying it.

**Comment by atifaziz** [comment]
> Will be honest - not fond of leading colon or slash in front of `snippet`. It adds to the confusing syntax more than simplifying it.

Agree with the slash but I think `:snippet` works well. It's easy to remember because it's just the opposite of the opening. Just for fun, 🙃I want to throw this one out there although I think it has no chance of sticking with anyone:

// snippet name
// teppins

Still, I like that _snippet_ written backwards (_teppins_) is equally easier to pronounce when written forwards! Will anyone remember it?

I fear we will never reach a consensus between everyone's tastebuds so we should strive for a reasonable solution and the provide the here-doc as an escape hatch where it's open to the author's liking impromptu.

**Comment by SeanFeldman** [comment]
"teppins" let's not 😂

**Comment by SimonCropp** [comment]
thanks so much for all the input.

I decided to go with

```
// begin-snippet: MySnippetName
My Snippet Code
// end-snippet
```
